### ISSUE TITLE
Gagner du temps en parsant le DOM avec cheerio

### ISSUE THREAD

**Issue by dorian-marchal** [dieulot/jvforum#3]
Plutôt que de parser le DOM avec des regexes, tu pourrait gagner du temps en le parsant avec [cheerio](https://github.com/cheeriojs/cheerio).

C'est une implémentation du parser DOM de jQuery.

Par exemple, au lieu de ça :

```js
retour.title = false
if (matches = body.match(/<span id="bloc-title-forum">(.+)<\/span>/)) {
  retour.title = matches[1]
}
```

Tu pourrais faire ça :

```js
retour.title = $('#bloc-title-forum').text() || false;
```

**Comment by dieulot** [comment]
Ouais, ça a l’air sympa merci. Je vais tenter ça pour parser la liste des sujets.

**Comment by kiwec** [comment]
A noter que j'ai déjà fait des fonction pour parse avec cheerio, licence MIT donc tu peux copier/coller comme tu veux. C'est les fonctions parseX.

https://github.com/kiwec/bestofjv

**Comment by dieulot** [comment]
Du coup j’ai utilisé cheerio
