### ISSUE TITLE
Interface MP / CDV plus avancée

### ISSUE THREAD

**Issue by lc-guy** [dieulot/jvforum#31]
Ce serait sympa de pouvoir recevoir / envoyer des MPs direct depuis JVForum et de pouvoir s'abo / voir les abos, mais bon, je sais pas si c'est possible sans construire une interface entière pour les CDVs.

**Comment by dieulot** [comment]
MP prévus, abos non. Une interface entière pour les CDVs est prévu aussi.

Les suggestions sont à faire sur le topic officiel sinon, les issues sont plus réservées aux questions de développement. (C’est pas grave.)
