### ISSUE TITLE
Montrer les URL JVForum des liens jeuxvideo.com

### ISSUE THREAD

**Issue by dieulot** [dieulot/jvforum#65]
Au lieu de montrer le texte `http://www.jeuxvideo.com/forums/42-1000021-39674315-166-0-1-0-appli-jvforum-topic-officiel.htm` on devrait montrer `jvforum.fr/1000021/39674315-appli-jvforum-topic-officiel/166`. Comme ça le lien sera plus court et très peu souvent tronqué, et ce sera clair qu’on reste sur le site (les liens jeuxvideo.com qui ne concernent pas les forums s’ouvrent sur jeuxvideo.com).

**Comment by dorian-marchal** [comment]
Ça risque d'être compliqué pour les citations, non ? Tu vas reconvertir les liens `jvforum.fr/*` en `www.jeuxvideo.com/forums/*` au moment du post ?

**Comment by Angivare** [comment]
Il suffit de rajouter un attribut HTML aux liens modifiés pour qu'ils soient facilement repérables depuis JVCode.js, à partir de là on peut gérer ça en pre-process
