### ISSUE TITLE
Timezone réglée dans JVForum

### ISSUE THREAD

**Issue by Wonderfall** [dieulot/jvforum#9]
Histoire de limiter la configuration sur l'hôte, la timezone peut être réglée directement dans l'app node, avec `process.env.TZ` mais je trouve que [moment.js](http://momentjs.com/timezone/) est plus souple pour ça, à voir.

**Comment by dieulot** [comment]
Quel serait l’intérêt ? En production il faut que je règle la timezone au niveau du serveur pour MySQL.

**Comment by Wonderfall** [comment]
Un peu prématuré comme fermeture... Personnellement je n'ai pas besoin de régler au niveau de MySQL... Je ne comprends pas trop ce que tu veux dire par là. Après j'utilise des conteneurs, donc je dois raisonner différemment.

**Comment by dieulot** [comment]
Je dois régler le fuseau horaire au niveau du serveur (via `tzdata` sous Debian), notamment pour que MySQL enregistre les dates correctement.

**Comment by Wonderfall** [comment]
Personnellement, voici un `date` sur le conteneur MariaDB : `Thu Jul  7 15:46:34 UTC 2016`
Pas besoin de préciser un fuseau horaire autre que celui-là.

En revanche pour le conteneur JVForum, je dois aussi régler avec `tzdata`.
https://github.com/Wonderfall/jvforum_docker/blob/master/Dockerfile#L17-L19

Ce sont des conteneurs mais ça démontre bien qu'il n'y a pas besoin de régler le fuseau horaire pour MySQL. Je trouvais plus souple de régler ça directement au niveau de l'app, mais bon.

**Comment by dieulot** [comment]
Le problème d'un MySQL qui n'a pas les bons fuseaux horaires c'est que je ne peux pas faire de SELECT x WHERE telle date dans MySQL directement.
